"""
Shared helpers for the scripts/literature/ pipeline. Not a runnable script —
imported directly by 1-build_zotero_mapping.py, 2-copy_sources_and_build_index.py,
and 3-extract_markdown.py (same-directory import, no sys.path manipulation needed).
"""

from __future__ import annotations

import re
import unicodedata

_BRACE_RE = re.compile(r"\{([^{}]*)\}")
_PUNCT_RE = re.compile(r"[^\w\s]")
_WS_RE = re.compile(r"\s+")


def strip_bib_braces(title: str) -> str:
    """Unwrap BibTeX brace-escaping for display: "{ShuffleNet}" -> "ShuffleNet",
    nested/multi-word braces like "{IEEE}/{CVF}" -> "IEEE/CVF"."""
    s = title or ""
    prev = None
    while prev != s:
        prev = s
        s = _BRACE_RE.sub(r"\1", s)
    s = s.replace("\\%", "%").replace("\\&", "&")
    s = s.replace("---", "-").replace("--", "-")
    return s.strip()


def normalize_title(title: str) -> str:
    """Normalize a paper title for cross-source comparison (BibTeX vs. Zotero)."""
    s = strip_bib_braces(title)
    s = unicodedata.normalize("NFKD", s)
    s = "".join(ch for ch in s if not unicodedata.combining(ch))
    s = s.lower()
    s = _PUNCT_RE.sub("", s)
    s = _WS_RE.sub(" ", s).strip()
    return s


def fingerprint(title_norm: str, year: str | None, first_author_surname: str | None) -> str:
    """Primary match key: normalized title + year + first-author surname."""
    year_part = (year or "").strip()
    author_part = (first_author_surname or "").strip().lower()
    return f"{title_norm}|{year_part}|{author_part}"


def bib_first_author_surname(author_field: str | None) -> str:
    """Parse a BibTeX `author` field ("Surname, Given and Surname2, Given2 and ...")
    and return the first author's surname."""
    if not author_field:
        return ""
    first = author_field.split(" and ")[0].strip()
    if "," in first:
        return first.split(",")[0].strip()
    # Fallback for "Given Surname" (no comma) — last whitespace-separated token.
    parts = first.split()
    return parts[-1] if parts else ""


def render_index_md(rows: list[dict]) -> str:
    """Render the sources/INDEX.md table from a list of row dicts with keys:
    citekey, title, year, zotero_filename, has_pdf, has_extraction, note."""
    lines = [
        "<!-- Auto-generated by scripts/literature/2-copy_sources_and_build_index.py "
        "— do not hand-edit; re-run the pipeline instead. -->",
        "",
        "# Literature sources index",
        "",
        "Maps each `references.bib` citekey to its source PDF (copied from Zotero, "
        "gitignored — see `make sync-ignored`) and its Markdown extraction (tracked in git).",
        "",
        "| Citekey | Title | Year | Zotero Filename | PDF | Extraction | Notes |",
        "|---|---|---|---|---|---|---|",
    ]
    for row in rows:
        citekey = row.get("citekey", "")
        title = strip_bib_braces(row.get("title") or "").replace("|", "\\|")
        year = row.get("year") or ""
        zfile = (row.get("zotero_filename") or "").replace("|", "\\|")
        pdf = "Y" if row.get("has_pdf") else "N"
        extraction = "Y" if row.get("has_extraction") else "N"
        note = (row.get("note") or "").replace("|", "\\|")
        lines.append(
            f"| `{citekey}` | {title} | {year} | `{zfile}` | {pdf} | {extraction} | {note} |"
        )
    lines.append("")
    return "\n".join(lines)
